name: docker build
on: push

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: debian:testing
                    #- image: debian:stable ## TODO

        container:
            image: ${{ matrix.image }}

        steps:
            - name: Checkout main repository
              uses: actions/checkout@v3
            - name: Checkout developer-meta-files
              uses: actions/checkout@v3
              with:
                  repository: Kicksecure/developer-meta-files
                  path: developer-meta-files
            - name: System Basic Packages
              run: |
                  apt-get update
                  apt-get install --yes --no-install-recommends wine fpc adduser shellcheck lazarus git ca-certificates
            - name: System information
              run: |
                  whoami
                  cat /etc/os-release
                  uname -a
                  echo "${PATH}"
            - name: Create regular (non-root) user
              run: adduser --gecos "" --disabled-password user
            - name: Linux user file permissions fix
              run: chown --recursive user:user /__w/Whonix-Installer
            - name: Build and run test.exe
              run: su -s /bin/bash user -- ./test.sh
            - name: ppcross_install
              run: ./developer-meta-files/usr/bin/ppcross_install all
            - name: Build Installer
              run: su -s /bin/bash user -- ./build-dummy.sh
            - name: ShellCheck
              run: shellcheck ./*.sh

# vim: sw=4
